name: nd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy
  - pip:
    - absl-py==1.3.0
    - accelerate==0.15.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - base58==2.1.1
    - bitsandbytes==0.35.4
    - cachetools==5.2.0
    - click==8.1.3
    - configargparse==1.5.3
    - diffusers==0.10.2
    - docker-pycreds==0.4.0
    - filelock==3.8.2
    - fire==0.4.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.29
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - grpcio-tools==1.48.2
    - huggingface-hub==0.11.1
    - importlib-metadata==5.1.0
    - lightning-lite==1.8.5
    - lightning-utilities==0.3.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - msgpack==1.0.4
    - multiaddr==0.0.9
    - multidict==6.0.3
    - netaddr==0.8.0
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - packaging==22.0
    - pathtools==0.1.2
    - prefetch-generator==1.0.3
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.2
    - pymultihash==0.8.2
    - pytorch-lightning==1.8.5
    - pyyaml==6.0
    - regex==2022.10.31
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - safetensors==0.2.5
    - scipy==1.9.3
    - sentry-sdk==1.11.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - sortedcontainers==2.4.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==2.1.1
    - timm==0.6.12
    - tokenizers==0.13.2
    - torch-ema==0.3
    - torchmetrics==0.11.0
    - tqdm==4.64.1
    - transformers==4.25.1
    - varint==1.0.2
    - wandb==0.13.6
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - yarl==1.8.2
    - zipp==3.11.0